
export const categoryContants = {
  GETALLCATE_REQUEST: "GETALLCATE_REQUEST",
  GETALLCATE_SUCCESS: "GETALLCATE_SUCCESS",
  GETALLCATE_FAIL: "GETALLCATE_FAIL",
}

export const productContants = {
  GETALL_PRODUCT_REQUEST: "GETALL_PRODUCT_REQUEST",
  GETALL_PRODUCT_SUCCESS: "GETALL_PRODUCT_SUCCESS",
  GETALL_PRODUCT_FAIL: "GETALL_PRODUCT_FAIL",
}